/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'NotifyHuman': EventHandler<never, never>
    'GetStatus': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetFleet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ApproveIntervention': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'system.patch_route'; data: never }>
    'AgentNegotiation': EventHandler<never, { topic: 'system.patch_route'; data: never }>
    'AgentJudge': EventHandler<never, { topic: 'system.patch_route'; data: never }>
    'AdminCommand': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'system.patch_route'; data: never }>
    'PatchReality': EventHandler<never, never>
    'DetectConflict': EventHandler<never, { topic: 'agent.negotiate'; data: never }>
    'SimulateFuture': EventHandler<never, { topic: 'ai.analyze_risk'; data: never } | { topic: 'mission.tick'; data: never }>
    'StartMission': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'mission.tick'; data: never }>
    'ServeDashboard': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AgentMeteorologist': EventHandler<never, never>
  }
    
}